// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA3HTZzg2E6frAg3GGD2ySXb0vTU_PJfU',
    appId: '1:175663381244:web:97a2ec3dc3dd8fa4f8b579',
    messagingSenderId: '175663381244',
    projectId: 'remindlogin-20d74',
    authDomain: 'remindlogin-20d74.firebaseapp.com',
    storageBucket: 'remindlogin-20d74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjxBtJHtmspnSFMGU2Og78yY9-Xd_xOZc',
    appId: '1:175663381244:android:09cd95727217d928f8b579',
    messagingSenderId: '175663381244',
    projectId: 'remindlogin-20d74',
    storageBucket: 'remindlogin-20d74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKzoQiDl0dqjLDKE1OLbHdbg6AcYHulPM',
    appId: '1:175663381244:ios:194c7f23fd1cf7cef8b579',
    messagingSenderId: '175663381244',
    projectId: 'remindlogin-20d74',
    storageBucket: 'remindlogin-20d74.firebasestorage.app',
    iosClientId: '175663381244-nedvfahnmg67b3bkblput52rva322pdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.remind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKzoQiDl0dqjLDKE1OLbHdbg6AcYHulPM',
    appId: '1:175663381244:ios:194c7f23fd1cf7cef8b579',
    messagingSenderId: '175663381244',
    projectId: 'remindlogin-20d74',
    storageBucket: 'remindlogin-20d74.firebasestorage.app',
    iosClientId: '175663381244-nedvfahnmg67b3bkblput52rva322pdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.remind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA3HTZzg2E6frAg3GGD2ySXb0vTU_PJfU',
    appId: '1:175663381244:web:a40cf809582fb786f8b579',
    messagingSenderId: '175663381244',
    projectId: 'remindlogin-20d74',
    authDomain: 'remindlogin-20d74.firebaseapp.com',
    storageBucket: 'remindlogin-20d74.firebasestorage.app',
  );

}